spring:
  application:
    name: user-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://config.platform:9000

      eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
